# Generated by Django 3.0.3 on 2020-07-20 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner_platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('selectable_size', models.CharField(choices=[('Small and large', 'Small and large'), ('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('small_price', models.FloatField(default=0, null=True)),
                ('large_price', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('timestamp', models.IntegerField()),
                ('price', models.FloatField()),
                ('items', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCreationTopping',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCreationExtra',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderExtra',
            fields=[
                ('subcreationextra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.SubCreationExtra')),
            ],
            bases=('orders.subcreationextra',),
        ),
        migrations.CreateModel(
            name='OrderTopping',
            fields=[
                ('pizzacreationtopping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.PizzaCreationTopping')),
            ],
            bases=('orders.pizzacreationtopping',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('selectable_size', models.CharField(choices=[('Small and large', 'Small and large'), ('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('small_price', models.FloatField(default=0, null=True)),
                ('large_price', models.FloatField(default=0, null=True)),
                ('selectable_extra_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_1_subs', to='orders.SubCreationExtra')),
                ('selectable_extra_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_2_subs', to='orders.SubCreationExtra')),
                ('selectable_extra_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_3_subs', to='orders.SubCreationExtra')),
                ('selectable_extra_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_4_subs', to='orders.SubCreationExtra')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.BooleanField(default=False)),
                ('checkout_items', models.CharField(max_length=64, null=True)),
                ('cart_version', models.IntegerField(default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('selectable_size', models.CharField(choices=[('Small and large', 'Small and large'), ('Small', 'Small'), ('Large', 'Large')], max_length=64)),
                ('small_price', models.FloatField(default=0, null=True)),
                ('large_price', models.FloatField(default=0, null=True)),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Crust')),
                ('topping_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_1_pizzas', to='orders.PizzaCreationTopping')),
                ('topping_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_2_pizzas', to='orders.PizzaCreationTopping')),
                ('topping_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_3_pizzas', to='orders.PizzaCreationTopping')),
                ('topping_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping_4_pizzas', to='orders.PizzaCreationTopping')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salads', to='orders.Profile')),
                ('salad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_salads', to='orders.Salad')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_pastas', to='orders.Pasta')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='orders.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_dinner_platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('dinner_platter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_dinner_platters', to='orders.Dinner_platter')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_platters', to='orders.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('orderextra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OrderExtra')),
            ],
            bases=('orders.orderextra',),
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('ordertopping_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OrderTopping')),
            ],
            bases=('orders.ordertopping',),
        ),
        migrations.CreateModel(
            name='Cart_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='orders.Profile')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_subs', to='orders.Sub')),
                ('extra_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_1_cart_subs', to='orders.OrderExtra')),
                ('extra_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_2_cart_subs', to='orders.OrderExtra')),
                ('extra_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_3_cart_subs', to='orders.OrderExtra')),
                ('extra_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_4_cart_subs', to='orders.OrderExtra')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_pizzas', to='orders.Pizza')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.Profile')),
                ('topping_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_1_cart_pizzas', to='orders.OrderTopping')),
                ('topping_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_2_cart_pizzas', to='orders.OrderTopping')),
                ('topping_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_3_cart_pizzas', to='orders.OrderTopping')),
                ('topping_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_4_cart_pizzas', to='orders.OrderTopping')),
            ],
        ),
    ]
